spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
      read-write: jdbc:mysql://localhost:3306/thinner?zeroDateTimeBehavior=convertToNull
      read-only: jdbc:mysql://localhost:3306/thinner?zeroDateTimeBehavior=convertToNull
    username: root
    password: gabriella93
    hikari:
      maximum-pool-size: 30
      auto-commit: false
      connection-init-sql: